language: minimal

sudo: required

services:  
  - docker

install:  
  - docker build -t cbors-test:${PYTHON_VERSION}-${TRAVIS_COMMIT} --build-arg PYTHON_VERSION=${PYTHON_VERSION} -f docker/Dockerfile.test .

script:
  - docker run --rm --security-opt seccomp=unconfined cbors-test:${PYTHON_VERSION}-${TRAVIS_COMMIT} tox -e ${TOXENV}

matrix:
  include:
    - env: PYTHON_VERSION=3.5 TOXENV=py35-nocov
    - env: PYTHON_VERSION=3.6 TOXENV=py36-nocov
    - env: PYTHON_VERSION=3.7 TOXENV=py37-cov TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
