language: rust

rust:
  - nightly

sudo: required

services:  
  - docker

before_script:
  - rustup component add rustfmt || true
  - rustup component add clippy || true

jobs:
  include:
    - stage: lint
      script: 
        - cargo fmt --all -- --check
        - cargo clippy

script:
  - docker build -t cbors-test:${PYTHON_VERSION}-${TRAVIS_COMMIT} --build-arg PYTHON_VERSION=${PYTHON_VERSION} -f docker/Dockerfile.test .
  - docker run --rm --security-opt seccomp=unconfined -e CI=true --env-file <(env | grep ^TRAVIS) cbors-test:${PYTHON_VERSION}-${TRAVIS_COMMIT} tox -e ${TOXENV}

deploy:
  - provider: script
    script: docker run --rm -e PYO3_PACK_PASSWORD=${PYPI_PASSWORD} cbors-test:${PYTHON_VERSION}-${TRAVIS_COMMIT} pyo3-pack publish -u ${PYPI_USER}
    on:
      tags: true

env:
  global:
    - PYPI_USER=mjkoo
    - secure: "eTH70XJr3+tdymTf0QKhRE5Pl4HMvvLZlP4le/vz/J4MAg7hU/Cdil8TyuVtTB37F56fw/LvQD6VORPZJiR8TQK/RgZE4/JC/o5MJtwyf/OczyZfZ9i6v0EYNBgUG2+tOIlLrWJXfiiqUafFHAOTsBSkweSMvx1Rszrlrwz9v3WNgY/R+HyeXN1VDELShdBbKmdL2g0e1CW8j+i0BMfJZDWmZy0Ee89B/efdTu1bRJHcPgrJ1ZpKfmPbcqPftQbBr/Ugzv1Gl/2/j5Gux2IdJnCCUujSaTJ/frTe9HsV6k4VYMotuKZ5eQO6TcjUkgT+It5NUsQ0NLNv3c8FUTY03u8l8/sf6khT/DAxOMtkj7qVojmOWK5U5Yxexp0+B0zv8+8XVl4IUt4blVRNEjROENMn4aJYp1HNraQf9FunwJkzkJRiuvzHVUJXv+KKv6lfgeN0LjLwB68xSYvTEb6A/6igDRkzU7glozkVfn77/jTtfPSdyLkE9DE8k5zX2xjq3/SIDhFqkngq/3uaySyLzYRInU6fHzzMjcEkryszkZ98Xho3x+gquZpd0RSlWbKeTHFULDM0jXYY3Rc2k0BK7FljNFppB+4MXZ4tYSqoVNrGbG99wxv+Sipy3PlyxRU7iyJDKbz6+nM5gl7EdjIAJMXAJ3eszyaypwAR5pdJ95k="

matrix:
  include:
    - env: PYTHON_VERSION=3.5 TOXENV=py35-nocov
    - env: PYTHON_VERSION=3.6 TOXENV=py36-nocov
    - env: PYTHON_VERSION=3.7 TOXENV=py37-cov
