language: minimal

sudo: required

services:  
  - docker

install:  
  - docker build -t cbors-test:${PYTHON_VERSION}-${TRAVIS_COMMIT} --build-arg PYTHON_VERSION=${PYTHON_VERSION} -f docker/Dockerfile.test .

script:
  - docker run --rm --security-opt seccomp=unconfined -e TRAVIS_JOB_ID=${TRAVIS_JOB_ID} cbors-test:${PYTHON_VERSION}-${TRAVIS_COMMIT} tox -e ${TOXENV}

deploy:
  - provider: script
    script: docker run --rm -e PYO3_PACK_PASSWORD=${PYPI_PASSWORD} cbors-test:${PYTHON_VERSION}-${TRAVIS_COMMIT} pyo3-pack publish -u ${PYPI_USER}
    on:
      tags: true

env:
  global:
    - PYPI_USER=mjkoo
    - secure: "dIcnrBPDVyhMuaAavyKNZKVrzonIEMB3N+NeuMukVXekf3dwlzKcI+0eoH/PsoLtNHYiLd/rNF0wFFOv6fqwb/Z3pOnjaSAzzkx5JWGYAZQfHYPAQZJmE9ydp9MAetcfZysrd+Qe9rdXViRX9ZSihslCa6OGARkbiqgOjasHNmH2dRe8qfj6AHojl9da2KbXthUUU+Y506rA+GQtGOon1p1KhNFb25vUN5iN2bnYtm7zgAGhNFq82L2i/qQkI063XeaZzY8YKXsmDKcoFtrgypPMSPI0y9nflQ/RyTmMLS8sT2JDYX2uvFkW9UQAMWQU7DGi272VdZbUXJs7BtMvSgGjJ9ngdZ2KGzcCjg6UN40SZTEk5rZ6hO4hzaAsaFuQ+ncnr3b+CrkQjatF6dH6dugYkzPZU4WLPGUaC4qjKZ+ehBB+hu1Qw4oxuz2GtFkUXTBgDeubes3J0hr4qqhYppXvu/rfKYeAk3RWpMsFDK2LpuuLZ2qTtXgVH3Zoa+n3haDo55Iu6Tg5R1o35oeJfDCuvGCofkZE2sF1EwZuraC3nyerySU3KDIBpUyf33+ypHYqsVlyetY0BtUI2TPDi/NwQflrEZE4Qsmy51jReweaZQU8Tm8b2br2zhcLO6lsQzgKAoNfpTrGU1k0VuK6mynO3bS8Ki3SVk9NjnQK0CQ="

matrix:
  include:
    - env: PYTHON_VERSION=3.5 TOXENV=py35-nocov
    - env: PYTHON_VERSION=3.6 TOXENV=py36-nocov
    - env: PYTHON_VERSION=3.7 TOXENV=py37-cov
