# Based off nightly Rust image at https://hub.docker.com/r/rustlang/rust/
ARG PYTHON_VERSION=3.7

FROM python:${PYTHON_VERSION}-slim
LABEL maintainer="Maxwell Koo <mjkoo90@gmail.com>"

# Apt deps
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        binutils-dev \
        ca-certificates \
        cmake \
        curl \
        libcurl4-openssl-dev \
        libelf-dev \
        libdw-dev \
        libiberty-dev \
        wget \
        zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

# Build and install kcov
ENV KCOV_VERSION=36
RUN wget https://github.com/SimonKagstrom/kcov/archive/v${KCOV_VERSION}.tar.gz && \
    tar -xf "v${KCOV_VERSION}.tar.gz" && \
    cd kcov-${KCOV_VERSION} && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf kcov-${KCOV_VERSION}

# Install rust
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH
RUN wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init" && \
    chmod +x rustup-init && \
    ./rustup-init -y --no-modify-path --default-toolchain nightly && \
    rm rustup-init && \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME

RUN pip3 install maturin tox

WORKDIR /usr/src/cbors
COPY . ./

CMD ["tox"]
