FROM rustlang/rust:nightly-slim
LABEL maintainer="Maxwell Koo <mjkoo90@gmail.com>"

RUN apt-get update && apt-get -y install \
        python3 \
        python3-dev \
        python3-pip \
    && rm -rf /var/lib/apt-lists/*

RUN pip3 install pytest
RUN cargo install pyo3-pack

WORKDIR /usr/src/cbors
COPY . ./

RUN pyo3-pack build && \
    pip3 install --no-index --find-links=target/wheels cbors

CMD ["pytest"]
